### ISSUE TITLE
/home/kali/Desktop/myapp/AndroidManifest.xml

### ISSUE THREAD

**Issue by mori1209** [ryanking13/android-SSL-unpinning#4]
└─# python3 patch.py /home/kali/Desktop/myapp.apk                   
I: Using Apktool 2.4.1 on myapp.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
Traceback (most recent call last):
  File "/home/kali/Desktop/android-SSL-unpinning/patch.py", line 120, in <module>
    main()
  File "/home/kali/Desktop/android-SSL-unpinning/patch.py", line 102, in main
    patch_manifest_file(str(manifest_file))
  File "/home/kali/Desktop/android-SSL-unpinning/patch.py", line 35, in patch_manifest_file
    tree = ET.parse(manifest_file)
  File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/kali/Desktop/myapp/AndroidManifest.xml'

**Comment by dolodi** [comment]
same
